from __future__ import annotations

import argparse
import math
import re
import shutil
import subprocess
from pathlib import Path


QBOOT_SECTOR_ORDER = [0x0, 0x7, 0xE, 0x6, 0xD, 0x5, 0xC, 0x4, 0xB, 0x3, 0xA, 0x2, 0x9, 0x1, 0x8, 0xF]
SECTOR_SIZE = 256
TRACK_SIZE = 16 * SECTOR_SIZE
GAME_ENTRY = 0x0803
STARTUP_PREFIX = bytes((0xA2, 0xFF, 0x9A))


def parse_map_exports(map_path: Path, names: list[str]) -> dict[str, int]:
    wanted = set(names)
    found: dict[str, int] = {}
    pattern = re.compile(r"(\S+)\s+([0-9A-Fa-f]{6})\s+R(?:L|E)A")

    for raw_line in map_path.read_text().splitlines():
        for match in pattern.finditer(raw_line):
            name = match.group(1)
            if name in wanted:
                found[name] = int(match.group(2), 16)

    missing = [name for name in names if name not in found]
    if missing:
        raise SystemExit(f"missing exports in map file: {', '.join(missing)}")
    return found


def extract_startup_targets(binary_path: Path) -> dict[str, int]:
    image = binary_path.read_bytes()
    startup = image[:12]
    if startup[:3] != STARTUP_PREFIX:
        raise SystemExit(f"unexpected startup prefix: {startup[:3].hex()}")
    if startup[3] != 0x20 or startup[6] != 0x20 or startup[9] != 0x4C:
        raise SystemExit(f"unexpected startup trampoline layout: {startup.hex()}")

    helper_target = startup[4] | (startup[5] << 8)
    zerobss_target = startup[7] | (startup[8] << 8)
    callmain_target = startup[10] | (startup[11] << 8)
    return {
        "startup_helper_entry": helper_target,
        "zerobss_entry": zerobss_target,
        "callmain_entry": callmain_target,
        "startup_zerobss_call": GAME_ENTRY + 6,
        "startup_callmain_jump": GAME_ENTRY + 9,
    }


def analyze_startup_helper(binary_path: Path, helper_addr: int) -> dict[str, int]:
    image = binary_path.read_bytes()
    base = GAME_ENTRY
    start = helper_addr - base
    window = image[start:start + 96]
    signature = bytes((0xAD, 0x00, 0xBF, 0x38, 0xE9, 0x4C, 0x48, 0xD0))
    index = window.find(signature)
    if index < 0:
        raise SystemExit(f"startup helper probe signature not found at ${helper_addr:04X}")

    first_branch = helper_addr + index + 7
    first_offset = window[index + 8]
    if first_offset >= 0x80:
        first_offset -= 0x100
    first_fallback = (first_branch + 2 + first_offset) & 0xFFFF

    second_pattern = bytes((0xAD, 0x6F, 0xBF, 0xC9, 0x01, 0xD0))
    second_index = window.find(second_pattern, index + 8)
    if second_index < 0:
        raise SystemExit(f"startup helper secondary probe signature not found at ${helper_addr:04X}")
    second_branch = helper_addr + second_index + 5
    second_offset = window[second_index + 6]
    if second_offset >= 0x80:
        second_offset -= 0x100
    second_fallback = (second_branch + 2 + second_offset) & 0xFFFF
    if first_fallback != second_fallback:
        raise SystemExit(
            f"startup helper fallback mismatch: ${first_fallback:04X} vs ${second_fallback:04X}"
        )

    return {
        "startup_helper_probe_patch": first_branch,
        "startup_helper_probe_fallback": first_fallback,
    }


def write_rwts_symbols(build_dir: Path, rwts_dir: Path) -> Path:
    map_path = build_dir / "iimperialism.map"
    binary_path = build_dir / "iimperialism"
    exports = parse_map_exports(
        map_path,
        [
            "_main",
            "_init_overlays",
            "_ui_init",
            "_clear_screen",
            "_print_bold",
            "_draw_picture_at",
            "_beep",
            "__HIMEM__",
            "zerobss",
            "callmain",
        ],
    )
    startup = extract_startup_targets(binary_path)
    helper = analyze_startup_helper(binary_path, startup["startup_helper_entry"])
    if startup["zerobss_entry"] != exports["zerobss"]:
        raise SystemExit(
            f"startup zerobss target ${startup['zerobss_entry']:04X} does not match map export ${exports['zerobss']:04X}"
        )
    if startup["callmain_entry"] != exports["callmain"]:
        raise SystemExit(
            f"startup callmain target ${startup['callmain_entry']:04X} does not match map export ${exports['callmain']:04X}"
        )

    symbol_lines = [
        "; generated by tools/build_rwts_boot.py from the live RWTS build",
        f"game_entry            = ${GAME_ENTRY:04X}",
        f"startup_helper_entry  = ${startup['startup_helper_entry']:04X}",
        f"zerobss_entry         = ${startup['zerobss_entry']:04X}",
        f"callmain_entry        = ${startup['callmain_entry']:04X}",
        f"startup_zerobss_call  = ${startup['startup_zerobss_call']:04X}",
        f"startup_callmain_jump = ${startup['startup_callmain_jump']:04X}",
        f"startup_helper_probe_patch = ${helper['startup_helper_probe_patch']:04X}",
        f"startup_helper_probe_fallback = ${helper['startup_helper_probe_fallback']:04X}",
        f"main_entry            = ${exports['_main']:04X}",
        f"init_overlays_entry   = ${exports['_init_overlays']:04X}",
        f"ui_init_entry         = ${exports['_ui_init']:04X}",
        f"clear_screen_entry    = ${exports['_clear_screen']:04X}",
        f"print_bold_entry      = ${exports['_print_bold']:04X}",
        f"draw_picture_at_entry = ${exports['_draw_picture_at']:04X}",
        f"beep_entry            = ${exports['_beep']:04X}",
        f"himem_entry           = ${exports['__HIMEM__']:04X}",
    ]

    output = rwts_dir / "rwts_symbols.inc"
    output.write_text("\n".join(symbol_lines) + "\n")
    return output


def rewrite_lines(src: Path, dst: Path, replacements: dict[str, str]) -> None:
    out_lines: list[str] = []
    for raw_line in src.read_text().splitlines():
        stripped = raw_line.lstrip()
        if stripped.startswith("!to "):
            continue
        replaced = False
        for key, new_line in replacements.items():
            if stripped.startswith(key):
                out_lines.append(new_line)
                replaced = True
                break
        if not replaced:
            out_lines.append(raw_line)
    dst.write_text("\n".join(out_lines) + "\n")


def assemble(acme: Path, source: Path, output: Path, symbollist: Path | None = None) -> None:
    cmd = [str(acme)]
    if symbollist is not None:
        cmd += ["-l", str(symbollist)]
    cmd += ["-o", str(output), str(source)]
    subprocess.run(cmd, check=True)


def write_sector(image: bytearray, track: int, sector: int, payload: bytes) -> None:
    if len(payload) > SECTOR_SIZE:
        raise ValueError(f"sector payload too large: {len(payload)} bytes")
    offset = track * TRACK_SIZE + sector * SECTOR_SIZE
    image[offset:offset + SECTOR_SIZE] = payload.ljust(SECTOR_SIZE, b"\x00")


def write_stage2(image: bytearray, stage2: bytes, track: int) -> int:
    sectors = math.ceil(len(stage2) / SECTOR_SIZE)
    if sectors > 16:
        raise ValueError(f"stage-2 payload exceeds one track: {sectors} sectors")
    padded = stage2.ljust(sectors * SECTOR_SIZE, b"\x00")
    for index in range(sectors):
        sector = QBOOT_SECTOR_ORDER[index]
        chunk = padded[index * SECTOR_SIZE:(index + 1) * SECTOR_SIZE]
        write_sector(image, track, sector, chunk)
    return sectors


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    parser.add_argument("--build", required=True)
    parser.add_argument("--disk", required=True)
    args = parser.parse_args()

    root = Path(args.root)
    build_dir = Path(args.build)
    disk_path = Path(args.disk)

    acme = root / "third_party" / "acme" / "src" / "acme.exe"
    qboot_src = root / "third_party" / "qboot" / "QBOOT.S"
    prorwts_src = root / "third_party" / "prorwts" / "PRORWTS.S"
    continue_src = root / "asm" / "rwts" / "continue.s"

    if not acme.exists():
        raise SystemExit(f"ACME not found: {acme}")

    rwts_dir = build_dir / "rwts_boot"
    if rwts_dir.exists():
        shutil.rmtree(rwts_dir)
    rwts_dir.mkdir(parents=True)
    rwts_symbols = write_rwts_symbols(build_dir, rwts_dir)

    configured_prorwts = rwts_dir / "prorwts_cfg.s"
    rewrite_lines(
        prorwts_src,
        configured_prorwts,
        {
            "enable_floppy": "                enable_floppy = 1       ; build script override",
            "override_adr": "                override_adr = 1       ; build script override",
            "enable_write": "                enable_write = 1       ; build script override",
            "might_exist": "                might_exist  = 1       ; build script override",
        },
    )
    prorwts_text = configured_prorwts.read_text()
    prorwts_text = prorwts_text.replace(
        "                lda DEVNUM\n",
        "                lda #$60\n",
        1,
    )
    original_prefix_probe = """                ldx #1
                stx namlo
                inx
                stx namhi

                jsr MLI
                !byte $c7
                !word c7_parms
                ldx $200
                dex
                stx sizelo
                bmi +++

readblock       jsr MLI
                !byte $80
                !word x80_parms

                lda #<(readbuff+4)
                sta bloklo
                lda #>(readbuff+4)
                sta blokhi
inextent        ldy #0
                lda (bloklo), y
                pha
                and #$d0

                ;watch for subdirectory entries

                cmp #$d0
                bne +

                lda (bloklo), y
                and #$0f
                tax
                iny
--              lda (bloklo), y
                cmp (namlo), y
                beq ifoundname

                ;match failed, move to next directory in this block, if possible

-
+               pla
                clc
                lda bloklo
                adc #$27
                sta bloklo
                bcc +

                ;there can be only one page crossed, so we can increment instead of adc

                inc blokhi
+               cmp #<(readbuff+$1ff) ;4+($27*$0d)
                lda blokhi
                sbc #>(readbuff+$1ff)
                bcc inextent

                ;read next directory block when we reach the end of this block

                lda readbuff+2
                ldx readbuff+3
                bcs +

ifoundname      iny
                dex
                bne --
                lda (namlo), y
                cmp #'/'
                bne -
                tya
                eor #$ff
                adc sizelo
                sta sizelo
                clc
                tya
                adc namlo
                sta namlo
                pla
                and #$20
                bne ++
                ldy #KEY_POINTER+1
                lda (bloklo), y
                tax
                dey
                lda (bloklo), y
!if enable_floppy=1 {
                sta unrblocklo+1
                stx unrblockhi+1
} ;enable_floppy
                sta unrhddblocklo+1
                stx unrhddblockhi+1
+               sta x80_parms+4
                stx x80_parms+5
++              lda sizelo
                bne readblock
"""
    if original_prefix_probe not in prorwts_text:
        raise SystemExit("ProRWTS prefix probe block not found in upstream source")
    prorwts_text = prorwts_text.replace(
        original_prefix_probe,
        "                jmp +++\n",
        1,
    )
    configured_prorwts.write_text(prorwts_text)
    prorwts_bin = rwts_dir / "prorwts.bin"
    assemble(acme, configured_prorwts, prorwts_bin, rwts_dir / "prorwts.lbl")
    stage2 = prorwts_bin.read_bytes()

    configured_continue = rwts_dir / "continue_cfg.s"
    rewrite_lines(
        continue_src,
        configured_continue,
        {
            "; rwts_symbols_include": f'!source "{rwts_symbols.as_posix()}"',
        },
    )
    continue_bin = rwts_dir / "continue.bin"
    assemble(acme, configured_continue, continue_bin)

    stage2_track = 0x22
    stage2 = continue_bin.read_bytes()
    if len(stage2) > 0x400:
        raise SystemExit("continuation code exceeds $0400-$07FF staging window")
    stage2 += b"\x00" * (0x400 - len(stage2))
    stage2 += prorwts_bin.read_bytes()
    stage2_sectors = math.ceil(len(stage2) / SECTOR_SIZE)

    configured_qboot = rwts_dir / "qboot_cfg.s"
    rewrite_lines(
        qboot_src,
        configured_qboot,
        {
            "sectors": f"        sectors   = ${stage2_sectors:02X}         ; build script override",
            "firsttrk": f"        firsttrk  = ${stage2_track:02X}         ; build script override",
            "firstsec": "        firstsec  = $00         ; build script override",
            "address": "        address   = $04         ; build script override",
            "entry": "        entry     = $0400       ; build script override",
        },
    )
    qboot_text = configured_qboot.read_text()
    original_jump = "        jmp     $bf00           ;DOS 3.3 launcher entrypoint"
    replacement_jump = "        jmp     seekread        ; direct stage-2 load"
    if original_jump not in qboot_text:
        raise SystemExit("qboot launcher jump not found in upstream source")
    qboot_text = qboot_text.replace(original_jump, replacement_jump)
    configured_qboot.write_text(qboot_text)
    qboot_bin = rwts_dir / "qboot.bin"
    assemble(acme, configured_qboot, qboot_bin)

    image = bytearray(disk_path.read_bytes())
    if len(image) != 35 * TRACK_SIZE:
        raise SystemExit(f"unexpected disk size: {len(image)} bytes")

    qboot_padded = qboot_bin.read_bytes().ljust(3 * SECTOR_SIZE, b"\x00")
    for index, sector in enumerate((0x0, 0xE, 0xD)):
        start = index * SECTOR_SIZE
        write_sector(image, 0, sector, qboot_padded[start:start + SECTOR_SIZE])

    write_stage2(image, stage2, stage2_track)

    disk_path.write_bytes(image)


if __name__ == "__main__":
    main()
